# Generated by Django 3.2.23 on 2024-01-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetail',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='AssetDetails'),
        ),
        migrations.AddField(
            model_name='housedetail',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='HouseDetails'),
        ),
    ]
