# Generated by Django 3.2.23 on 2024-01-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0002_auto_20240116_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetuserdescription',
            name='aplication_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetuserdescription',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.asset'),
        ),
    ]
