# Generated by Django 4.2.3 on 2023-12-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UAA', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
