# Generated by Django 3.2.23 on 2024-01-13 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetDescriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Description Type',
                'db_table': 'Asset Description Type',
            },
        ),
        migrations.CreateModel(
            name='AssetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('on_sales', models.BooleanField(default=False)),
                ('needs_tenants', models.BooleanField(default=True)),
                ('amount_per_type', models.BigIntegerField(default=50000)),
                ('time_duration', models.BigIntegerField(default=3)),
                ('asset_description', models.JSONField(default=[])),
                ('number_asset_present', models.BigIntegerField(default=1)),
                ('is_house', models.BooleanField(default=False)),
                ('is_tower', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.asset')),
            ],
            options={
                'verbose_name': 'Asset Detail',
                'db_table': 'Asset Detail',
            },
        ),
        migrations.CreateModel(
            name='AssetRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.asset')),
            ],
            options={
                'verbose_name': 'Asset Role',
                'db_table': 'Asset Role',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'db_table': 'District',
            },
        ),
        migrations.CreateModel(
            name='OwnershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ownership Type',
                'db_table': 'Ownership Type',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Status',
                'db_table': 'Payment Status',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('bod', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='Photo')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Detail',
                'db_table': 'User Detail',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ward', to='AssetManagement.userdetails')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.district')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_ward', to='AssetManagement.userdetails')),
            ],
            options={
                'verbose_name': 'Ward',
                'db_table': 'Ward',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_regions', to='AssetManagement.userdetails')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_regions', to='AssetManagement.userdetails')),
            ],
            options={
                'verbose_name': 'Region',
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=100)),
                ('have_tenant', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=True)),
                ('tenant', models.JSONField(blank=True, null=True)),
                ('owner', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assetdetail')),
            ],
            options={
                'verbose_name': 'House Detail',
                'db_table': 'House Detail',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_district', to='AssetManagement.userdetails'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.region'),
        ),
        migrations.AddField(
            model_name='district',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_district', to='AssetManagement.userdetails'),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_countries', to='AssetManagement.userdetails'),
        ),
        migrations.AddField(
            model_name='country',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_countries', to='AssetManagement.userdetails'),
        ),
        migrations.CreateModel(
            name='AssetUserDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_user_description_type', to='AssetManagement.userdetails')),
                ('description_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assetdescriptiontype')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_asset_user_description_type', to='AssetManagement.userdetails')),
            ],
            options={
                'verbose_name': 'Asset User Description',
                'db_table': 'Asset User Description',
            },
        ),
        migrations.CreateModel(
            name='AssetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('description', models.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assetdetail')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_asuser', to='AssetManagement.userdetails')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assetrole')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_asuser', to='AssetManagement.userdetails')),
            ],
            options={
                'verbose_name': 'Asset User',
                'db_table': 'Asset User',
            },
        ),
        migrations.CreateModel(
            name='AssetUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_use', to='AssetManagement.userdetails')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_use', to='AssetManagement.userdetails')),
            ],
            options={
                'verbose_name': 'Asset Use',
                'db_table': 'Asset Use',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_type', to='AssetManagement.userdetails')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_type', to='AssetManagement.userdetails')),
            ],
            options={
                'verbose_name': 'Asset Type',
                'db_table': 'Asset Type',
            },
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_asstatus', to='AssetManagement.userdetails')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_asstatus', to='AssetManagement.userdetails')),
            ],
            options={
                'verbose_name': 'Asset Status',
                'db_table': 'Asset Status',
            },
        ),
        migrations.AddField(
            model_name='assetrole',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rotype', to='AssetManagement.userdetails'),
        ),
        migrations.AddField(
            model_name='assetrole',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_rotype', to='AssetManagement.userdetails'),
        ),
        migrations.CreateModel(
            name='AssetMaintance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mainannce_date', models.DateField()),
                ('is_maintained', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('maintained_by', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assetdetail')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_type_maintanance', to='AssetManagement.userdetails')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_type_maintanance', to='AssetManagement.userdetails')),
            ],
            options={
                'verbose_name': 'Asset maintinance',
                'db_table': 'Asset maintinance',
            },
        ),
        migrations.AddField(
            model_name='assetdetail',
            name='asset_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assetstatus'),
        ),
        migrations.AddField(
            model_name='assetdetail',
            name='asset_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assetuse'),
        ),
        migrations.AddField(
            model_name='assetdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_detail', to='AssetManagement.userdetails'),
        ),
        migrations.AddField(
            model_name='assetdetail',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.ownershiptype'),
        ),
        migrations.AddField(
            model_name='assetdetail',
            name='paynent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.paymentstatus'),
        ),
        migrations.AddField(
            model_name='assetdetail',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assettype'),
        ),
        migrations.AddField(
            model_name='assetdetail',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_detail', to='AssetManagement.userdetails'),
        ),
        migrations.AddField(
            model_name='assetdetail',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.ward'),
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_category', to='AssetManagement.userdetails')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_category', to='AssetManagement.userdetails')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'db_table': 'Asset Category',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assetcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_asset', to='AssetManagement.userdetails'),
        ),
        migrations.AddField(
            model_name='asset',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_asset', to='AssetManagement.userdetails'),
        ),
    ]
