# Generated by Django 4.2.3 on 2023-12-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='update_by',
        ),
    ]
