# Generated by Django 3.2.23 on 2023-12-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetdescriptiontype',
            options={'verbose_name': 'Asset Description Type'},
        ),
        migrations.RemoveField(
            model_name='assetdescriptiontype',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetdescriptiontype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assetdescriptiontype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='assetdescriptiontype',
            name='update_by',
        ),
        migrations.AlterField(
            model_name='assetdetail',
            name='asset_description',
            field=models.JSONField(default={}),
        ),
        migrations.AlterModelTable(
            name='assetdescriptiontype',
            table='Asset User Description Type',
        ),
        migrations.CreateModel(
            name='AssetUserDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_user_description_type', to='AssetManagement.userdetails')),
                ('description_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetManagement.assetdescriptiontype')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_asset_user_description_type', to='AssetManagement.userdetails')),
            ],
            options={
                'verbose_name': 'Asset User Description',
                'db_table': 'Asset User Description',
            },
        ),
    ]
