# Generated by Django 3.2.23 on 2023-12-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0002_auto_20231226_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='assetuser',
            name='description',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
