# Generated by Django 4.2.3 on 2023-12-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0002_remove_paymentstatus_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownershiptype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ownershiptype',
            name='update_by',
        ),
    ]
